#!/bin/bash

# ARGS: up|down container

CONTAINER="$2"

mkdir -p /var/run/lxd-portforward

if [ "$1" = "up" ]
then
  ACTION="-A"
  IP="$(lxc info "$CONTAINER" | grep eth0 | awk '{print $3}')"
  echo "$IP" > "/var/run/lxd-portforward/$CONTAINER"
else
  ACTION="-D"
  IP="$(cat "/var/run/lxd-portforward/$CONTAINER")"
fi

for line in $(grep "^$CONTAINER" /etc/lxd/lxd-portforward.conf)
do
  FROM="$(echo $line | cut -f2 -d:)"
  TO="$(echo $line | cut -f3 -d:)"
  iptables -t nat $ACTION PREROUTING -p tcp -i eth0 --dport "$FROM" -j DNAT --to-destination "$IP:$TO" \
    -m comment --comment "lxd-portforward: *:$FROM -> $CONTAINER:$TO"
done

