#!/bin/bash
#
# WARNING?: No LXD CALLS ALLOWED IN THIS SCRIPT. THEY WILL DEADLOCK
#
# ARGS: <container> lxc <hook> ...

if [ "$2" = "lxc" -a "$3" = "pre-start" ]
then
  at -M now 2> /dev/null <<UPSCRIPT
sleep 5;
/etc/lxd/lxd-portforward-helper up $1
UPSCRIPT
else
  at -M now 2> /dev/null <<DOWNSCRIPT
sleep 5;
/etc/lxd/lxd-portforward-helper down $1
DOWNSCRIPT
fi
